resources:
  repositories:
  - type: github
    endpoint: ch-robinson-internal
    ref: refs/heads/master
    repository: templates
    name: ch-robinson-internal/DevOps.Azure.Pipeline.Library
  - type: github
    endpoint: ch-robinson-internal
    ref: refs/heads/master
    repository: rating
    name: ch-robinson-internal/Rating.SharedDeploy
extends:
  parameters:
    deployEnvironments: ${{ parameters.deployEnvironments }}
  template: rating-shared-iis-api-pipeline.yml@rating
parameters:
- default:
  - groupNumber: 2
    name: dev
    cluster: 10
  - groupNumber: 2
    name: int
    cluster: 10
  - groupNumber: 2
    name: trn
    cluster: 10
  - groupNumber: 2
    name: prd
    cluster: 10
  name: deployEnvironments
  type: object
trigger:
  branches:
    include:
    - development
    - master
  paths:
    exclude:
    - monitoring/*
variables:
- parameters:
    appName: AuxiliaryAuditor
  template: rating-shared-iis-api-variables.yml@rating
pr:
  branches:
    include:
    - development
    - master
  paths:
    exclude:
    - monitoring/*
name: $(Major).$(Minor).$(Build).$(Revision)
